attendence/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('page.urls')),
    path('', include('django.contrib.auth.urls')),

]

page/urls.py
from django.urls import path
from . import views

app_name = 'page'

urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('logout/', views.logout, name='l_out'),
    path('register/', views.register_data, name='register'),
    path('trace/<str:method>/', views.trace_card, name='trace'),
    path('trace/', views.trace_card, name='trace'),
    path('count/', views.count_person, name='count'),
    path('entry/', views.entry_data, name='entry'),
    path('timetable_wise-count/', views.timetable_wise_count, name='timetable_wise_count'),
    path('time_wise-count/', views.time_wise_count, name='time_wise_count'),
    # path('weekly_data/', views.weekly_data, name='weekly_data'),
    # path('monthly_data/', views.monthly_data, name='monthly_data'),
    path('attendance/', views.attendance_data, name='attendance_data'),
    path('view_timetable/', views.view_timetable, name='view_timetable'),
    path('analyse_attendance/', views.analyse_attendance, name='analyse_attendance'),

    path('excel-trace/', views.trace_excel, name='trace_excel'),
    path('excel-time_wise_count/', views.time_wise_excel, name='excel-time_wise_excel'),
    path('excel-timetable_count/', views.timetable_wise_excel, name='timetable_excel'),
    path('time_wise_pdf/', views.time_wise_pdf, name='time_wise_pdf'),
    path('timetable_pdf/', views.timetable_pdf, name='timetable_pdf'),
    path('trace_pdf/', views.trace_pdf, name='trace_pdf'),
    path('what_is_rfid/', views.what_is_rfid, name='what_is_rfid'),
    path('why_rfid/', views.why_rfid, name='why_rfid'),
    path('how_it_works/', views.how_it_works, name='how_it_works'),
    path('save_attendance/', views.save_attendance, name='save_attendance'),
    path('attendance_excel_pdf/', views.attendance_excel_pdf, name='attendance_excel_pdf'),
    path('attendance_excel_pdf/<str:method>/', views.attendance_excel_pdf, name='attendance_excel_pdf'),

    path('entry_/', views.TagApiView.as_view(), name='entry_'),
    # path('entry_/<str:tag_>/<str:area_>/', views.TagApiView.as_view(), name='entry_')

]

templates/analyse.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'static_files/css/analyse.css' %}"/>
{% endblock %}


{% block content %}
<div class="myDiv">
    <div class="container1">
        <form method="get">
            <br>
            {% if is_course %}
                <input type="hidden" name="course" value="{{is_course}}">
            {% endif %}
            {% if is_year %}
                <input type="hidden" name="year" value="{{is_year}}">
            {% endif %}
            <div class="row">
                <div class="col">
                    <h4 class="name">Start date</h4>
                    <select class="form-select" aria-label="Default select example" name="DATE1">
                        <option disabled="disabled" selected="selected">--Today's date is default</option>
                        {% for x in date_list %}
                        <option> {{x}}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col">
                    <h4 class="name">End date</h4>
                    <select class="form-select" aria-label="Default select example" name="DATE2">
                        <option disabled="disabled" selected="selected">--Today's date is default</option>
                        {% for x in date_list %}
                        <option> {{x}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            {% if is_course and is_year %}
            <br>
            <h4 class="name">Roll No</h4>
            <div class="row">
                <div class="col">
                    <input type="number" name="std_roll" class="form-control" placeholder="Student Roll"
                           aria-label="Roll No" autocomplete="off">
                </div>
            </div>
            {% endif %}

            <br>
            <div class="row">
                <div class="col">
                    <div class="text-center">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
            <br>
        </form>
    </div>
</div>
<hr class="line">

{% if messages %}
<div class="alert alert-danger" role="alert">
    {% for message in messages %}
    <h4><b>{{ message }}</b></h4>
</div>
{% endfor %}
<hr class="line">
{% endif %}

{% if main_graph %}
<div class="row">
    <div class="col">
        <div class="text-center">
            {% if not is_course and not is_year %}
            <h4>Year Wise Attendance Count for all Courses</h4>
            {% elif is_course and is_year%}
            <h4>Batch Wise Attendance Count for {{is_course}}-{{is_year}}</h4>
            {% elif is_course %}
            <h4>Year Wise Attendance Count for {{is_course}}</h4>
            {% endif %}
            {% if start_date and end_date %}
            <h4>from {{start_date}} to {{end_date}}</h4>
            {% endif %}
            <div class="table_width_control" id="shadow_table">
                <img src="data:image/png;base64, {{main_graph | safe}}">
            </div>
        </div>
    </div>
</div>
<hr class="line">

{% endif %}

<div class="container">
    {% for course, graph in compare_graph.items %}
    <div class="row">
        <div class="alert alert-danger" role="alert">
            {% if is_course %}
            <a href="{% url 'page:analyse_attendance' %}?course={{is_course}}&year={{course}}">
                <h4><b>{{course}}</b></h4>
            </a>
            {% else %}
            <a href="{% url 'page:analyse_attendance' %}?course={{course}}">
                <h4><b>{{course}}</b></h4>
            </a>
            {% endif %}
        </div>
    </div>
    <div class="row">
        <div class="text-center">
            <div class="table_width_control" id="shadow_table">
                <img src="data:image/png;base64, {{graph | safe}}">
            </div>
        </div>
    </div>
    <hr class="line">
    {% endfor %}
</div>

{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">

    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <meta name="description" content="">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css"
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!--<link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">-->
    <meta name="theme-color" content="#563d7c">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <meta name="viewport" content="width=device-width,initial-scale=1, shrink-to-fit=no">
    {% block head %}
    {% endblock %}

    {% load static %}
    <link rel="stylesheet" href="{% static '/static_files/css/base.css' %}"/>

{% block style %}
{% endblock %}

    <!-- Custom styles for this template -->

</head>
<body>


{% if user.is_authenticated %}

<div class="container-fluid">
    <div class="row flex-nowrap">
        <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
            <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
                <br>
                <span class="fs-5 d-none d-sm-inline">Menu...</span>
                <br>
                <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
                    <li>
                        <br>
                        <a href="{% url 'page:homepage' %}">
                            <i class="fa fa-home" style="font-size:26px;"></i>
                            <span class="fs-5 d-none d-sm-inline">Homepage</span>
                        </a>
                    </li>
                    <li>
                        <hr class="style-two">
                        <a href="{% url 'page:attendance_data' %}">
                            <i class="fa fa-calendar" style="font-size:22px"></i>
                            <span class="fs-5 d-none d-sm-inline">Attendance</span>
                        </a>
                    <li>
                        <hr class="style-two">
                        <a href="{% url 'page:view_timetable' %}">
                            <i class="fa fa-th-list" style="font-size:21px"></i>
                            <span class="fs-5 d-none d-sm-inline">TimeTable</span>
                        </a>
                    </li>
                    <li>
                        <hr class="style-two">
                        <a href="{% url 'page:analyse_attendance' %}">
                            <i class="fa fa-bar-chart" style="font-size:21px"></i>
                            <span class="fs-5 d-none d-sm-inline">Analyse</span>
                        </a>
                    </li>
                    <li>
                        <br><br><br>
                        <a href="{% url 'logout' %}">
                            <i class="fa fa-sign-out" style="font-size:24px"></i>
                            <span class="fs-5 d-none d-sm-inline">Sign_Out</span>
                        </a>
                    </li>
                </ul>
            </div>
        </div>
        {% endif %}
        <div class="col py-3">

            <!-- Main content here-->
            <nav class="navbar navbar-expand-sm navbar-dark fixed-top bg-dark">
                <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarMenu">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarMenu">
                    <!--<div class="collapse navbar-collapse" id="topnav">-->
                    <ul class="navbar-nav mr-auto">
                            <li class="nav-item active">
                                <div class="text-center">
                                <a class="nav-link" href="{% url 'page:what_is_rfid' %}">WHAT IS RFID</a>
                                    </div>
                            </li>
                            <li class="nav-item active">
                                <div class="text-center">
                                <a class="nav-link" href="{% url 'page:how_it_works' %}">HOW IT WORKS</a>
                                    </div>
                            </li>
                            <li class="nav-item active">
                                <div class="text-center">
                                <a class="nav-link" href="{% url 'page:why_rfid' %}">WHY RFID</a>
                                    </div>
                            </li>
                    </ul>
                </div>
            </nav>

            {% if user.is_authenticated %}

            <div class="wrapper">
                <br>
                {% block content %}
                {% endblock %}
            </div>

        </div>
    </div>
</div>


<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
{% block script %}
{% endblock %}
{% else %}
<br><br>
<div class="container">
    <div class="column">
        <div class="row">
            <div class="col">
                <h1>You are not logged in.</h1>
                <hr>
                <h2>Click <a href="{% url 'login' %}">here</a> to log in again</h2>
                <br>
            </div>
        </div>
        <br>
    </div>
</div>
{% endif %}
</body>
</html>

templates/count_selection.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register tab</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
</head>
<body>
<style>
#gallery-text-left{
  /* Added */
  width: 50%;
}
#gallery-paragraph-1{
  border-left:8px solid #1c2e4a;
  border-radius:4px;
  padding-left:15px;
  /* Added */
  word-wrap: break-word;
  font-size:25px;
  margin-left:10px;
  color:black;
}
#gallery-paragraph-2{
  border-left:8px solid #1c2e4a;
  border-radius:4px;
  padding-left:15px;
  font-size:25px;
  margin-left:10px;
  color:black;
}
#gallery-text-right{
  /* Added */
  width: 50%;
}
#gallery-text-quote-left{
  width:500px;
  margin-left:70px;
  font-size:30px;
}
#gallery-text-quote-right{
  width:500px;
  margin-left:70px;
  font-size:30px;
}
.hp{
                  position:relative;
                  background-color: #36454f;
                  color:white;
                  left:665px;
                  top:-1px;
                  line-height: 40px;
                  width:185px;
                  height:40px;
                  border-radius: 6px;
                  padding: 0  22px;
                  font-size: 16px;
                  outline:none;
                  overflow:hidden;
              }
#SUBMIT_1{
width:100px;
height:30px;
font-size:16px;
color:white;
margin-left:200px;
}
</style>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'page:what_is_rfid' %}">WHAT IS RFID</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'page:how_it_works' %}">HOW IT WORKS</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'page:why_rfid' %}">WHY RFID</a>
      </li>
        <li>

            <div id = "fname">
                <a href="{% url 'page:homepage' %}">
                    <button  class="hp" name="home" type = "submit" id = "button" onclick="setColor('button', '#36454f')" ><i class = "fa fa-home &nbsp">   HOMEPAGE</i></button>
                    </a>
     </div>
        </li>
    </ul>
      <script>
    var count = 1;
    function setColor(button, color) {
        var property = document.getElementById(button);
        if (count == 0) {
            property.style.backgroundColor = "white"
            property.style.color = "#36454f"
            count = 1;
        }
        else {
            property.style.backgroundColor = "white"
	    property.style.color = "#36454f"
            count = 0;
        }
    }
    </script>
  </div>
</nav>
<br><br>
<br><br>
<div id="gallery-text">

    <div id="gallery-text-left" style="float:left">
    <p id="gallery-text-quote-left" style="font-family:Century Gothic; color:#1c2e4a"><b>TIME - TABLE  WISE COUNT<b></p>
    <p id="gallery-paragraph-1" style="font-family:Georgia">
    Here  we can find the count of students <br>for a particular lecture or practical<br>
    Based on the timetable for the course we <br>want to find count, we can input subject<br> and get<br>
    student count for that time interval<br><br>
        <a href="{% url 'page:timetable_wise-count' %}">
    <button id="SUBMIT_1" style="font-family:Century Gothic; background-color:#1c2e4a"><b>Submit</b></button></a>
    </p>
    </div>
    <div id="gallery-text-right" style="float:left">
    <p id="gallery-text-quote-right" style="font-family:Century Gothic; color:#1c2e4a"><b>TIME - WISE COUNT</B>
	</p>
    <p id="gallery-paragraph-2" style="font-family:Georgia">
    Here we can find the count of <br>students for any time interval we <br>want<br>
    The start and end time can be <br>inputted to get the count for student <br>for that interval<br><br>
        <a href="{% url 'page:time_wise-count' %}">

    <button id="SUBMIT_1" style="font-family:Century Gothic; background-color:#1c2e4a"><b>Submit</b></button></a>
    </p>
    </div>
</div>
</body>
</html>

templates/entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>entry tab</title>
</head>
<body>
{% if user.is_authenticated %}
<form method="get">
    <h2 class = "TAG_ID">TAG ID</h2>
     <input class = "TAG_ID" type = "text" name = "TAG_ID" required><br>
    <h2 class = "AREA">AREA </h2>
    <select class="option" name = "AREA" required>
     <option disabled="disabled" selected="selected">--Choose Your Course</option>
     <option> Computer Lab 1-a </option>
        <option> Computer Lab 1-b </option>
     <option> Computer Lab 2-a </option>
        <option> Computer Lab 2-b </option>
     <option> Computer Lab 3-a </option>
        <option> Computer Lab 3-b </option>
     <option> Computer Lab 4-a </option>
        <option> Computer Lab 4-b </option>
     <option> Electronics lab </option>
     <option> Sports Room </option>
     <option> Library </option>
     </select>
     <button class="submit" type = "submit">SUBMIT</button>
  </form>
{% if messages %}
<div class="alert alert-danger" role="alert">
{% for message in messages %}
{{ message }}
</div>
{% endfor %}
{% endif %}

<br><br><br><br>
<a href="{% url 'page:homepage' %}">
     <button class="hp" type = "submit" id = "button" onclick="setColor('button', '#36454f')" ><i class = "fa fa-home &nbsp">   HOMEPAGE</i></button>
         </a>

{% else %}
<div>
<h2>You are not currently logged in, to login click <a href="{% url 'login' %}">here</a></h2>
</div>
    {% endif %}
</body>
</html>

templates/how_it_works.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" href="{% static '/static_files/css/how_it_works.css' %}"/>
{% endblock %}

{% block content %}
<br>
<div class="text-center">
    <h1>HOW IT WORKS</h1>
</div>

<div class="myDiv">
    <div class="container">
        <br>
        <p>
            Faraday's principle of magnetic induction is the basis of near-field coupling
            between a Reader and Tag. </p>
        <p>A Reader passes a large alternating current through
            a reading coil, resulting in an alternating magnetic field in its locality. </p>
        <hr class="line">
        <div class="text-center">
            <div class="footer">
                <img src="{% static 'page/images/RFID_propogation.png' %}" style="width:70%">
            </div>
        </div>
        <hr class="line">
        <p>If you place a Tag that incorporates a smaller coil in this
            field, an alternating voltage will appear across it. If this voltage is rectified
            and coupled to a capacitor, a reservoir of charge accumulates, which you can then
            use to power the Tag chip.</p>
        <hr class="line">
        <div class="text-center">
            <div class="footer">
                <img src="{% static 'page/images/coupling.png' %}" style="width:70%">
            </div>
        </div>
        <hr class="line">
        <p>Tags that use near-field coupling send data back to the Reader using-load modulation.
            This current is proportional to the load
            applied to the Tag's coil (hence load modulation).</p>
        <p>RFID Tags based on far-field
            emissions capture EM waves propagating from a dipole antenna
            attached to the Reader. A smaller dipole antenna in the Tag receives this
            energy as an alternating potential difference that appears across the arms
            of the dipole. </p>
        <hr class="line">
        <div class="text-center">
            <div class="footer">
                <img src="{% static 'page/images/RFID.jpg' %}" style="width:70%">
            </div>
        </div>
        <hr class="line">
        <p>A diode can rectify this potential and link it to a capacitor,
            which will result in an accumulation of energy in order to power its electronics.
            However, unlike the inductive designs, the Tags beyond the range of the Reader's
            near field, can't transmitted information back to the Reader using load
            modulation.
        </p>
        <hr class="line">
    </div>
</div>

{% endblock %}

templates/nav.html
<html>
    <head>
        <link rel="stylesheet" href="nav.css">
    </head>
    <body>
        <nav>
            <ul>
                <li id="active" class="one">Details</li>
                <li class="two">Chat</li>
                <li class="three">Attendance</li>
                <li class="four">Assignments</li>
            </ul>
        </nav>
        <div id="main">
        <div id="one">
            <p>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis necessitatibus tenetur corporis inventore itaque atque cupiditate iste ratione reprehenderit a eveniet, quod ullam hic modi nulla error animi sit nobis
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus iusto accusantium odit, rem molestiae, corporis asperiores, assumenda cumque tempora minus fuga pariatur delectus maxime distinctio saepe nihil obcaecati tempore quisquam?
                Modi earum neque esse ullam molestias laudantium impedit explicabo dolores maxime quo? Voluptatem exercitationem, asperiores voluptate rerum sequi iure dolorum dignissimos provident, quo minus facere ad odio, libero suscipit nulla!
                Quidem quasi cupiditate odio quos sapiente animi aperiam amet illum, dignissimos quo perferendis incidunt, eaque eveniet praesentium magnam quod quaerat impedit inventore! Ducimus necessitatibus ipsum doloremque, ab error tempore? Minus.
                Quam consectetur quisquam, voluptatem mollitia exercitationem non unde neque quasi ullam animi reiciendis asperiores obcaecati, tempore natus inventore necessitatibus sequi aperiam alias quis incidunt magni, perspiciatis temporibus perferendis. Fugiat, vel.
                Culpa vel nihil at possimus distinctio quos molestias deserunt sequi ullam eius omnis, rem odit reprehenderit a sunt, aliquid necessitatibus ab ut autem pariatur labore, similique inventore facere ex. Molestias.
            </p>
        </div>
        <div id="two">
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae optio voluptate vel neque? Nesciunt perspiciatis voluptatibus maxime animi. Quasi ex dicta nihil veritatis sint unde eligendi praesentium ab repudiandae rem!
        </div>
        </div>
        <script src="nav.js"></script>
    </body>
</html>

templates/pdf_maker.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>pdf_maker</title>
    <style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}
</style>
</head>
<body>


{% for x in table %}

<h2>Weekly Entries in {{ x.0.0 }}</h2>
<table>
  <tr>
    {% for head in heading %}
    <th>{{ head }}</th>
    {% endfor %}
  </tr>
    {% for line in x %}
  <tr>
      {% for block in line %}
    <th>{{ block }}</th>
{% endfor %}
  </tr>
{% endfor %}
</table>
{% endfor %}
</body>
</html>

templates/timetable.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static '/static_files/css/timetable.css' %}"/>
{% endblock %}

{% block content %}
{% if user.is_authenticated %}


<div class="myDiv">
    <form method="get">
        <div class="container1">
            <br><br>
            <div class="row">
                <div class="col">
                    <h4 class="name">Select Course</h4>
                    <select id="sel1" class="form-select" aria-label="Default select example" name="course"
                            onchange="depend(this.id,'sel2')">
                        <option disabled="disabled" selected="selected">--Choose Your Course</option>
                        {% for course, id in year_id.items %}
                        <option id="{{id | safe}}">{{course}}</option>
                        {% endfor %}
                    </select>
                </div>

                <div class="col">
                    <h4 class="name">Select Year</h4>
                    <select id="sel2" class="form-select" aria-label="Default select example" name="year">
                        <option disabled="disabled" selected="selected">--Choose Your Course</option>
                    </select>
                </div>
            </div>
            <hr class="line">
            <div class="row">
                <div class="col">
                    <h4 class="name">Any specific date</h4>
                    <select class="form-select" aria-label="Default select example" name="DATE">
                        <option disabled="disabled" selected="selected">--Today's date is default</option>
                        {% for x in date %}
                        <option> {{x}}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>

            <div class="row">
                <div class="col">
                    <div class="text-center">
                        <hr class="line">
                        <button type="submit" class="btn btn-primary">Submit</button>
                    </div>
                </div>
            </div>
            <br><br>
        </div>
    </form>
</div>

<div class="container">
    <br>
    <hr class="line">
</div>
<div class="container">
    <div>
        {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
            <h4><b>{{ message }}</b></h4>
        </div>
        {% endfor %}
        <hr class="line">
        {% endif %}
    </div>
</div>

<div class="container">
    <div class="column_simple">
        <div id="lg1" class="alert-alert-danger" role="alert">
            {% if course %}
            <h4>COURSE : <b>{{course}}</b></h4>
            {% endif %}
            {% if year %}
            <h4>YEAR : <b>{{year}}</b></h4>
            {% endif %}
            {% if day %}
            <h4>DAY : <b>{{day}}</b></h4>
            {% endif %}
        </div>
    </div>

    <div class="column_simple">
        {% if table %}
        <a href="{% url 'page:timetable_excel' %}?course={{course}}&date={{user_date}}&year={{year}}">
            <button type="submit" class="btn btn-danger">Get Excel</button>
        </a>
        <a href="{% url 'page:timetable_pdf' %}?course={{course}}&date={{user_date}}&year={{year}}">
            <button type="submit" class="btn btn-danger">Get Pdf</button>
        </a>
        {% endif %}
    </div>
</div>

<br>

{% if table %}
<div class="container">
    {%for table_by_id in table%}
    <div class="table_width_control" id="shadow_table">
        {{table_by_id | safe}}
    </div>
    <hr class="line">
    {% endfor %}
</div>
{% endif %}

{% endif %}

{% block script %}
<script type="text/javascript" src="{% static '/static_files/js/save_attendance.js' %}"></script>
{% endblock %}


{% endblock %}

templates/timetable_pdf.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
   <style>
table {
  font-family: arial, sans-serif;
  border-collapse: collapse;
  width: 100%;
}

td, th {
  border: 1px solid #dddddd;
  text-align: left;
  padding: 8px;
}

tr:nth-child(even) {
  background-color: #dddddd;
}

    </style>
</head>
<body>
<font size="+2"><b>Showing Timetable Count for : {{user_date}}</b></font><br>
<font size="+2"><b>Day : {{day}}</b></font><br>
<font size="+2"><b>Course : {{course}}</b></font><br>
<font size="+2"><b>Year : {{year}}</b></font>
<br>

{% if table %}
<table>
    <tr>
        {% for head in table_head %}
    <th bgcolor="grey">{{head}}</th>
        {% endfor %}
  </tr>
    {% for row in table %}
    <tr>
    {% for val in row %}
    <td>{{val}}</td>
    {% endfor %}
        </tr>
    {% endfor %}
</table>
{% endif %}

</body>
</html>